### ISSUE TITLE
Rebrush hermes frontend

### ISSUE THREAD

**Issue by wingsofovnia** [socialedge/hermes#168]
The current frontend is a piece of ~~shit~~ spaghetti code that is very hard to maintain. I think it's a good time to rewrite it from scratch coz implementing new features turns out into exceptional pain.

Some ideas about new frontend:
- Still AngularJS (the only thing we are "good" at)
- ES6
- **Components based** code

Todo list:
- [x] Init AngularJS+Webpack+ES6 project (done: #166)
- [x] Attach OpenAPI definitions (#167) to generate js client (done: #184)
- [x] Implement Agency page (closes #120) (done: #193)
- [ ] Implement Stops page
- [ ] Implement Lines page
- [ ] Implement Schedules page
- [ ] Implement Schedule page (closes #161)
- [ ] Implement Schedule collisions

Also must close #139, #112
